export const ADJUSTMENTS_FETCHED = "ADJUSTMENTS_FETCHED"
export const ADJUSTMENTS_ERROR = "ADJUSTMENTS_ERROR"

export const SET_SELECTED_ADJUSTMENT = "SET_SELECTED_ADJUSTMENT"

// Creating reactions
export const CREATING_REACTION = "CREATING_REACTION"
export const REACTION_CREATED = "REACTION_CREATED"
export const REACTION_CREATED_ERROR = "REACTION_CREATED_ERROR"

export const REACTIONS_FETCHED = "REACTIONS_FETCHED" 
export const REACTIONS_ERROR = "REACTIONS_ERROR"